/* 
 * Copyright 2013 Matthias Huebner
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.shu4m;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.apache.maven.execution.MavenSession;
import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;

/**
 * Generate Version class file from pom.xml
 * 
 * @author mhueb
 * 
 */
@Mojo(name = "generate-version", defaultPhase = LifecyclePhase.GENERATE_SOURCES)
public class VersionGenerator extends AbstractMojo {

  @Parameter(required = true, readonly = true, property = "project")
  private MavenProject mavenProject;

  @Parameter(required = true, readonly = true, property = "session")
  private MavenSession mavenSession;

  @Parameter(property = "sourcedir", required = true, defaultValue = "maver")
  private String source;

  @Parameter(property = "packagename", required = false, defaultValue = "")
  private String packageName;

  @Parameter(property = "classname", required = true, defaultValue = "Version")
  private String className;

  @Parameter(property = "encoding", required = true, defaultValue = "UTF-8")
  private String encoding;

  public void execute() throws MojoExecutionException, MojoFailureException {
    if (packageName == null || packageName.isEmpty())
      packageName = makeJavaName(mavenProject.getGroupId()) + "." + makeJavaName(mavenProject.getArtifactId()) + ".misc";

    getLog().info("Generating " + packageName + "." + className);

    File dir = new File(mavenProject.getBuild().getDirectory() + "/generated-sources/" + source + "/" + packageToPath(packageName));
    File buildInfoFile = new File(dir, className + ".java");

    makeDir(dir);

    try (OutputStreamWriter writer = new OutputStreamWriter(new FileOutputStream(buildInfoFile), encoding)) {
      writer.write("/*\n");
      writer.write(" * Generated by maver-plugin\n");
      writer.write(" */\n");
      writer.write("package ");
      writer.write(packageName);
      writer.write(";\n");
      writer.write("\n");
      writer.write("/**\n");
      writer.write(" * Project Version");
      writer.write(mavenProject.getGroupId());
      writer.write(":");
      writer.write(mavenProject.getArtifactId());
      writer.write("<br/>\n * <br/>\n");
      writer.write(" * Generated by maver-plugin\n");
      writer.write(" */\n");
      writer.write("public final class ");
      writer.write(className);
      writer.write(" {\n");
      writePropery(writer, "NAME", mavenProject.getName());
      writePropery(writer, "GROUPID", mavenProject.getGroupId());
      writePropery(writer, "ARTIFACTID", mavenProject.getArtifactId());
      writePropery(writer, "VERSION", mavenProject.getVersion());
      writePropery(writer, "BUILD_DATE", formatDate(mavenSession.getStartTime()));
      writePropery(writer, "DESCRIPTION", clean(mavenProject.getDescription()));
      writePropery(writer, "ORGANISATION", clean(getOrganisation()));
      writer.write("\n");
      writeSingletonGetter(writer);
      writeConstructor(writer);
      writeGetter(writer, "String", "getProjectName", "NAME");
      writeGetter(writer, "String", "getProjectVersion", "VERSION");
      writeGetter(writer, "String", "getGroupId", "GROUPID");
      writeGetter(writer, "String", "getArtifactId", "ARTIFACTID");
      writeGetter(writer, "String", "getBuildDate", "BUILD_DATE");
      writeGetter(writer, "String", "getDescription", "DESCRIPTION");
      writeGetter(writer, "String", "getOrganisation", "ORGANISATION");
      writer.write("\n}\n");
    }
    catch (IOException e) {
      throw new MojoFailureException("Failed to generate version file", e);
    }
  }

  private String packageToPath(String packageName) {
    return packageName.replace('.', '/');
  }

  private String makeJavaName(String name) {
    StringBuilder buff = new StringBuilder();
    for (int idx = 0; idx < name.length(); ++idx) {
      char charAt = name.charAt(idx);
      if (Character.isJavaIdentifierPart(charAt) || idx == 0 && Character.isJavaIdentifierStart(charAt))
        buff.append(charAt);
    }
    return buff.toString();
  }

  private String clean(String string) {
    return string == null ? "" : string.replace("\"", "\\\"").replace("\t", "\\t").replace("\n", "\\n").replace("\r", "\\r");
  }

  private String getOrganisation() {
    return mavenProject.getOrganization() == null ? "" : mavenProject.getOrganization().getName();
  }

  private String formatDate(Date date) {
    return date == null ? "" : new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ").format(date);
  }

  private void writeConstructor(OutputStreamWriter writer) throws IOException {
    writer.write("  private ");
    writer.write(className);
    writer.write("() {\n");
    writer.write("  }\n\n");
  }

  private void writeSingletonGetter(OutputStreamWriter writer) throws IOException {
    writer.write("  private static final ");
    writer.write(className);
    writer.write(" INSTANCE = new ");
    writer.write(className);
    writer.write("();\n\n");
    writer.write("  public static ");
    writer.write(className);
    writer.write(" get() {\n    return INSTANCE;\n  }\n\n");
  }

  private void writeGetter(OutputStreamWriter writer, String type, String name, String field) throws IOException {
    writer.write("  public ");
    writer.write(type);
    writer.write(" ");
    writer.write(name);
    writer.write("() {\n");
    writer.write("    return ");
    writer.write(field);
    writer.write(";\n  }\n\n");
  }

  private void writePropery(OutputStreamWriter writer, String name, String value) throws IOException {
    writer.write("\n  private static final String ");
    writer.write(name);
    writer.write(" = \"");
    writer.write(value);
    writer.write("\";\n");
  }

  private void makeDir(File dir) {
    if (dir == null || dir.exists())
      return;
    makeDir(dir.getParentFile());
    dir.mkdir();
  }
}